#!/bin/bash
if [ $# -ne 1 ]; then
    echo $0 file
    exit
fi
if [ -s $1 ];then
    name=$1
else
    if [ -s $1.grd ];then
	name=$1.grd
    else
	echo $1 or $1.grd are nonexistent.
	exit
    fi
fi


# max location
echo `grdinfo -M -C $name | gawk '{print($14,$15)}'`

