#!/bin/bash
#
# determine geoegraphic range of grd file for GMT
# $Id: grd2reg,v 1.2 2004/04/13 18:06:29 becker Exp becker $
#
if [ $# -ne 1 ];then
    echo $0: usage > "/dev/stderr"
    echo $0 tmp.grd > "/dev/stderr"
    echo  > "/dev/stderr"
    exit
fi

if [ -s $1 ];then
    name=$1
else
    if [ -s $1.grd ];then
	name=$1.grd
    else
	echo $1 or $1.grd are nonexistent.
	exit
    fi
fi
tmpd=`mktemp -d`
trap "rm -rf $tmpd ; exit" 0 1 2 15

sname=`basename $name`
dirname=`dirname $name`
owd=`pwd`

cd $tmpd

grdinfo -L0 -C $owd/$dirname/$sname | gawk '{print($2,$3,$4,$5)}'
